language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

env:
  PYTHONPATH=../

# command to install dependencies
install: "pip install -r requirements_dev.txt"

# script run flake8
before_script: flake8 .

# run tests
script: py.test
